package com.hospital.system.repository;
import com.hospital.system.model.*; import java.sql.Statement; import java.math.*; import java.util.*; import org.springframework.jdbc.core.*; import org.springframework.jdbc.support.GeneratedKeyHolder; import org.springframework.jdbc.support.KeyHolder; import org.springframework.stereotype.Repository;
@Repository public class BillingRepository { private final JdbcTemplate db; public BillingRepository(JdbcTemplate db){this.db=db;}
private final RowMapper<Bill> bm=(r,n)->{Bill b=new Bill();b.billId=r.getLong("bill_id");b.patientId=r.getLong("patient_id");b.appointmentId=(Long)r.getObject("appointment_id");b.patientName=r.getString("patient_name");b.billDate=r.getObject("bill_date",java.time.LocalDate.class);b.subtotal=r.getBigDecimal("subtotal");b.tax=r.getBigDecimal("tax");b.totalAmount=r.getBigDecimal("total_amount");b.paidAmount=r.getBigDecimal("paid_amount");b.balance=r.getBigDecimal("balance");b.status=r.getString("status");return b;};
private final RowMapper<BillItem> im=(r,n)->{BillItem i=new BillItem();i.billItemId=r.getLong("bill_item_id");i.billId=r.getLong("bill_id");i.serviceId=r.getLong("service_id");i.serviceName=r.getString("service_name");i.quantity=r.getInt("quantity");i.unitPrice=r.getBigDecimal("unit_price");i.amount=r.getBigDecimal("amount");return i;};
public List<Bill> all(){return db.query("SELECT * FROM v_bill_summary ORDER BY bill_id DESC",bm);} public Optional<Bill> one(Long id){return db.query("SELECT * FROM v_bill_summary WHERE bill_id=?",bm,id).stream().findFirst();}
public long create(Long patientId,Long appointmentId){KeyHolder k=new GeneratedKeyHolder(); db.update(c->{var x=c.prepareStatement("INSERT INTO bill(patient_id,appointment_id,bill_date,subtotal,tax,total_amount,status) VALUES(?,?,CURRENT_DATE,0,0,0,'UNPAID')",Statement.RETURN_GENERATED_KEYS); x.setLong(1,patientId); if(appointmentId==null)x.setNull(2,java.sql.Types.BIGINT);else x.setLong(2,appointmentId); return x;},k); return k.getKey().longValue();}
public int addItem(Long bill,Long service,int qty,BigDecimal price){return db.update("INSERT INTO bill_item(bill_id,service_id,quantity,unit_price,amount) VALUES(?,?,?,?,?)",bill,service,qty,price,price.multiply(BigDecimal.valueOf(qty)));}
public int removeItem(Long bill,Long item){return db.update("DELETE FROM bill_item WHERE bill_item_id=? AND bill_id=?",item,bill);} public List<BillItem> items(Long bill){return db.query("SELECT bi.*,hs.service_name FROM bill_item bi JOIN hospital_service hs ON hs.service_id=bi.service_id WHERE bi.bill_id=? ORDER BY bi.bill_item_id",im,bill);}
public Optional<BigDecimal> servicePrice(Long id){return db.query("SELECT price FROM hospital_service WHERE service_id=? AND active=TRUE",(r,n)->r.getBigDecimal(1),id).stream().findFirst();}
}
