USE hospital_system;
ALTER TABLE department ADD CONSTRAINT uq_department_name UNIQUE(department_name);
ALTER TABLE patient ADD CONSTRAINT uq_patient_phone UNIQUE(phone), ADD CONSTRAINT ck_patient_gender CHECK(gender IN ('MALE','FEMALE','OTHER'));
ALTER TABLE doctor ADD CONSTRAINT fk_doctor_department FOREIGN KEY(department_id) REFERENCES department(department_id) ON UPDATE CASCADE ON DELETE RESTRICT, ADD CONSTRAINT ck_doctor_fee CHECK(consultation_fee>=0), ADD CONSTRAINT ck_doctor_time CHECK(available_to>available_from);
ALTER TABLE appointment ADD CONSTRAINT fk_appt_patient FOREIGN KEY(patient_id) REFERENCES patient(patient_id) ON DELETE RESTRICT, ADD CONSTRAINT fk_appt_doctor FOREIGN KEY(doctor_id) REFERENCES doctor(doctor_id) ON DELETE RESTRICT, ADD CONSTRAINT uq_doctor_slot UNIQUE(doctor_id,appointment_date,appointment_time), ADD CONSTRAINT ck_appt_status CHECK(status IN ('BOOKED','COMPLETED','CANCELLED'));
ALTER TABLE hospital_service ADD CONSTRAINT uq_service_name UNIQUE(service_name), ADD CONSTRAINT ck_service_price CHECK(price>=0);
ALTER TABLE bill ADD CONSTRAINT fk_bill_patient FOREIGN KEY(patient_id) REFERENCES patient(patient_id) ON DELETE RESTRICT, ADD CONSTRAINT fk_bill_appt FOREIGN KEY(appointment_id) REFERENCES appointment(appointment_id) ON DELETE SET NULL, ADD CONSTRAINT uq_bill_appointment UNIQUE(appointment_id), ADD CONSTRAINT ck_bill_status CHECK(status IN ('UNPAID','PARTIALLY_PAID','PAID'));
ALTER TABLE bill_item ADD CONSTRAINT fk_item_bill FOREIGN KEY(bill_id) REFERENCES bill(bill_id) ON DELETE CASCADE, ADD CONSTRAINT fk_item_service FOREIGN KEY(service_id) REFERENCES hospital_service(service_id) ON DELETE RESTRICT, ADD CONSTRAINT ck_item_qty CHECK(quantity>0), ADD CONSTRAINT ck_item_amount CHECK(amount>=0);
ALTER TABLE payment ADD CONSTRAINT fk_payment_bill FOREIGN KEY(bill_id) REFERENCES bill(bill_id) ON DELETE CASCADE, ADD CONSTRAINT ck_payment_amount CHECK(amount>0), ADD CONSTRAINT ck_payment_method CHECK(payment_method IN ('CASH','CARD','UPI','BANK_TRANSFER'));
